---
apiVersion: v1
kind: Service
metadata:
  name: alertsystem
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: alertsystem

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertsystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertsystem
  template:
    metadata:
      labels:
        app: alertsystem
    spec:
      containers:
        - name: alertsystem
          image: ${IMAGE_REPO}/alertsystem-app:latest
          env:
            - name: MYSQL_HOST
              value: mysqldb
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
            - name: MYSQL_DATABASE
              value: finance_app
            - name: MYSQL_USER
              value: server
            - name: MYSQL_PASSWORD
              value: "1234"
            - name: KAFKA_BROKER
              value: kafka-broker:9092
          ports:
            - containerPort: 8081
      restartPolicy: Always
