---
apiVersion: v1
kind: Service
metadata:
  name: alertnotifier
spec:
  ports:
    - port: 8081
  selector:
    app: alertnotifier

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertnotifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertnotifier
  template:
    metadata:
      labels:
        app: alertnotifier
    spec:
      containers:
        - name: alertnotifier
          image: ${IMAGE_REPO}/alertnotifier-app:latest
          ports:
            - containerPort: 8081
      restartPolicy: Always
